server:
  port: 80
spring:
    application:
      name:  springcloud-zuul
#Eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: zuul.com
    prefer-ip-address: true
info:
   app.name: zyc.zuul
   company.name: zyc